## Auto generated by `proto_build_generator.sh`
load("@com_google_protobuf//bazel:proto_library.bzl", "proto_library")
load("@com_google_protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@com_google_protobuf//bazel:py_proto_library.bzl", "py_proto_library")

package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "%(car_type_lower)s_cc_proto",
    deps = [
        ":%(car_type_lower)s_proto",
    ],
)

proto_library(
    name = "%(car_type_lower)s_proto",
    srcs = ["%(car_type_lower)s.proto"],
)

py_proto_library(
    name = "%(car_type_lower)s_py_pb2",
    deps = [":%(car_type_lower)s_proto"],
)
